channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=24.0
- pip:
  - mlflow<3,>=2.2
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - psutil==5.9.5
  - scikit-learn==1.4.2
  - scipy==1.13.0
name: mlflow-env
